"""Add occupation field to StressRecord model

Revision ID: d46b19a50b6e
Revises: 5a30273e98cf
Create Date: 2025-04-13 23:43:38.376855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46b19a50b6e'
down_revision = '5a30273e98cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('stress_data')
    with op.batch_alter_table('stress_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stress_record', schema=None) as batch_op:
        batch_op.drop_column('occupation')

    op.create_table('stress_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('mood', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sleep_hours', sa.FLOAT(), nullable=True),
    sa.Column('coffee', sa.BOOLEAN(), nullable=True),
    sa.Column('water_intake', sa.FLOAT(), nullable=True),
    sa.Column('work_hours', sa.FLOAT(), nullable=True),
    sa.Column('stress_level', sa.FLOAT(), nullable=True),
    sa.Column('feelings', sa.TEXT(), nullable=True),
    sa.Column('activities', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('recommendation_text', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
