"""Initial migration with mood column

Revision ID: ecece5d1dc90
Revises: 
Create Date: 2025-04-08 20:48:23.867135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecece5d1dc90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stress_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_feelings', sa.Text(), nullable=True))

    with op.batch_alter_table('stress_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sleep_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('coffee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('water_intake', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activities', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('work_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('feelings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('stress_level', existing_type=sa.Float(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stress_record', schema=None) as batch_op:
        batch_op.alter_column('stress_level', existing_type=sa.Float(), nullable=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('feelings')
        batch_op.drop_column('work_hours')
        batch_op.drop_column('activities')
        batch_op.drop_column('water_intake')
        batch_op.drop_column('coffee')
        batch_op.drop_column('sleep_hours')
        batch_op.drop_column('mood')

    with op.batch_alter_table('stress_assessment', schema=None) as batch_op:
        batch_op.drop_column('additional_feelings')
    # ### end Alembic commands ###
